version: "3.6"

networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container

services:
  app:
    image: wstrinz/bsb_2022:0.1.0
    ports:
      - "4000:4000"
    env_file:
      - config/docker.env
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  db:
    image: postgres:13-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - pg-data:/pg-data
    ports:
      - "5432:5432"
    env_file:
      - config/docker.env
    networks:
      - webnet

volumes:
   pg-data: